version: '3'

services:

  postgres:
      restart: on-failure
      image: postgres:13
      container_name: docker-observatorio-postgres
      environment:
          POSTGRES_DB: observatorio
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          TZ: America/Recife
      ports:
          - 6603:5432
      volumes:
          - postgres-data:/var/lib/postgresql/data
            
  observatorio-api:
      restart: on-failure
      build:
          context: ./backend/observatorio
          dockerfile: Dockerfile
      container_name: docker-observatorio-api
      ports:
          - 8081:8081
      environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/observatorio
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
          SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
          SERVER_PORT: 8081

volumes:
  postgres-data: