-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.campus
(
    id bigint NOT NULL,
    cidade character varying(255) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT campus_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.campus_curso
(
    id bigint NOT NULL,
    id_campus bigint,
    id_curso bigint,
    CONSTRAINT campus_curso_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.curso
(
    id bigint NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT curso_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.curso_projeto
(
    id bigint NOT NULL,
    id_curso bigint,
    id_projeto bigint,
    CONSTRAINT curso_projeto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.projeto
(
    id bigint NOT NULL,
    conclusao text COLLATE pg_catalog."default",
    data_fim date,
    data_inicio date,
    fundamentacao text COLLATE pg_catalog."default",
    introducao text COLLATE pg_catalog."default",
    memoria_visual character varying(255) COLLATE pg_catalog."default",
    modalidade character varying(255) COLLATE pg_catalog."default",
    objetivos text COLLATE pg_catalog."default",
    pessoas_atendidas integer NOT NULL,
    publico_alvo character varying(255) COLLATE pg_catalog."default",
    resumo text COLLATE pg_catalog."default",
    suporte_financeiro double precision,
    titulo character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT projeto_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.campus_curso
    ADD CONSTRAINT fk3mshepgm6quv4vq1rtjf6gwqo FOREIGN KEY (id_campus)
    REFERENCES public.campus (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.campus_curso
    ADD CONSTRAINT fkfygfubuxt308yshd017kqy64l FOREIGN KEY (id_curso)
    REFERENCES public.curso (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.curso_projeto
    ADD CONSTRAINT fk9kok39eopmige40chgyiet6y4 FOREIGN KEY (id_projeto)
    REFERENCES public.projeto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.curso_projeto
    ADD CONSTRAINT fkaqqkuykyeg5po3f1byx7nll4s FOREIGN KEY (id_curso)
    REFERENCES public.curso (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;